# Generated by Django 4.1.5 on 2023-02-12 15:09

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import student.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=30,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="first_name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="last_name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "matric_number",
                    models.CharField(editable=False, max_length=7, unique=True),
                ),
                ("course_of_study", models.CharField(max_length=50)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100"),
                            ("200", "200"),
                            ("300", "300"),
                            ("400", "400"),
                            ("500", "500"),
                            ("600", "600"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("medicine", "MEDICINE"),
                            ("physiology", "DEPARTMENT OF PHYSIOLOGY"),
                            ("histology", "DEPARTMENT OF HISTOLOGY"),
                            ("community medicine", "DEPARTMENT OF COMMUNITY MEDICINE"),
                            (
                                "nutrition and dietetics",
                                "DEPARTMENT OF NUTRITION AND DIETETICS",
                            ),
                            ("anatomy", "Department of Anatomy"),
                            ("biochemistry", "Department of Biochemistry"),
                            (
                                "chaemical pathology",
                                "The Department of Chemical Pathology",
                            ),
                            (
                                "haematoloy and immunology",
                                "DEPARTMENT OF HAEMATOLOGY AND IMMUNOLOGY",
                            ),
                            ("micro biology", "DEPARTMENT OF MEDICAL MICROBIOLOGY"),
                            (
                                "software engineering",
                                "DEPARTMENT OF SOFTWARE ENGINEERING",
                            ),
                            ("computer science", "DEPARTMENT OF COMPUTER SCIENCE"),
                            (
                                "information technology",
                                "DEPARTMENT OF INFORMATION TECHNOLOGY",
                            ),
                            ("Relegious Studies", "DEPARTMENT OF RELIGIOUS STUDIES"),
                            (
                                "Languages and Literary Studies",
                                "Department of Languages and Literary Studies",
                            ),
                            (
                                "History and International Studies",
                                "Department of History and International Studies",
                            ),
                            (
                                "Music and Creative Arts",
                                "Department of Music and Creative Arts",
                            ),
                            ("Education", "Department of Education"),
                            (
                                "JURISPRUDENCE AND PUBLIC LAW",
                                "DEPARTMENT OF JURISPRUDENCE AND PUBLIC LAW",
                            ),
                            (
                                "PRIVATE AND COMMERCIAL LAW",
                                "DEPARTMENT OF PRIVATE AND COMMERCIAL LAW",
                            ),
                            (
                                "INTERNATIONAL LAW AND SECURITY STUDIES",
                                "DEPARTMENT OF INTERNATIONAL LAW AND SECURITY STUDIES",
                            ),
                            ("ACCOUNTING", "DEPARTMENT OF ACCOUNTING"),
                            ("FINANCE", "DEPARTMENT OF FINANCE"),
                            (
                                "BUSINESS ADMINISTRATION AND MARKETING",
                                "DEPARTMENT OF BUSINESS ADMINISTRATION AND MARKETING",
                            ),
                            (
                                "INFORMATION RESOURCES MANAGEMENT",
                                "DEPARTMENT OF INFORMATION RESOURCES MANAGEMENT",
                            ),
                            (
                                "MATERNAL & CHILD HEALTH",
                                "DEPARTMENT OF MATERNAL & CHILD HEALTH",
                            ),
                            ("ADULT HEALTH", "DEPARTMENT OF ADULT HEALTH"),
                            (
                                "MENTAL HEALTH & PSYCHIATRY",
                                "DEPARTMENT OF MENTAL HEALTH & PSYCHIATRY",
                            ),
                            ("COMMUNITY HEALTH", "DEPARTMENT OF COMMUNITY HEALTH"),
                            (
                                "MEDICAL LABORATORY",
                                "DEPARTMENT OF MEDICAL LABORATORY SCIENCE",
                            ),
                            ("PUBLIC HEALTH", "DEPARTMENT OF PUBLIC HEALTH"),
                            (
                                "AGRICULTURE AND INDUSTRIAL TECHNOLOG",
                                "DEPARTMENT OF AGRICULTURE AND INDUSTRIAL TECHNOLOGY",
                            ),
                            ("BASIC SCIENCES", "DEPARTMENT OF BASIC SCIENCES"),
                            ("MICROBIOLOGY", "DEPARTMENT OF MICROBIOLOGY"),
                            ("Economics", "Department of Economics"),
                            ("Mass Communication", "Department of Mass Communication"),
                            ("Political Science", "Department of Political Science"),
                            ("Social Work", "Department of Social Work"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "profile_picture",
                    models.FileField(
                        null=True, upload_to=student.models.UserModel.profilePicture
                    ),
                ),
                ("date_of_birth", models.DateTimeField(max_length=8, null=True)),
                (
                    "age",
                    models.IntegerField(
                        null=True, verbose_name=student.models.UserModel.calculate_age
                    ),
                ),
                ("update", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
