# Generated by Django 4.1.5 on 2023-02-12 16:37

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="course_of_study",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="first_name",
            field=models.CharField(
                max_length=30,
                null=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="first_name",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_name",
            field=models.CharField(max_length=30, null=True, verbose_name="last_name"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                    ("500", "500"),
                    ("600", "600"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="school",
            field=models.CharField(
                choices=[
                    ("medicine", "MEDICINE"),
                    ("physiology", "DEPARTMENT OF PHYSIOLOGY"),
                    ("histology", "DEPARTMENT OF HISTOLOGY"),
                    ("community medicine", "DEPARTMENT OF COMMUNITY MEDICINE"),
                    (
                        "nutrition and dietetics",
                        "DEPARTMENT OF NUTRITION AND DIETETICS",
                    ),
                    ("anatomy", "Department of Anatomy"),
                    ("biochemistry", "Department of Biochemistry"),
                    ("chaemical pathology", "The Department of Chemical Pathology"),
                    (
                        "haematoloy and immunology",
                        "DEPARTMENT OF HAEMATOLOGY AND IMMUNOLOGY",
                    ),
                    ("micro biology", "DEPARTMENT OF MEDICAL MICROBIOLOGY"),
                    ("software engineering", "DEPARTMENT OF SOFTWARE ENGINEERING"),
                    ("computer science", "DEPARTMENT OF COMPUTER SCIENCE"),
                    ("information technology", "DEPARTMENT OF INFORMATION TECHNOLOGY"),
                    ("Relegious Studies", "DEPARTMENT OF RELIGIOUS STUDIES"),
                    (
                        "Languages and Literary Studies",
                        "Department of Languages and Literary Studies",
                    ),
                    (
                        "History and International Studies",
                        "Department of History and International Studies",
                    ),
                    (
                        "Music and Creative Arts",
                        "Department of Music and Creative Arts",
                    ),
                    ("Education", "Department of Education"),
                    (
                        "JURISPRUDENCE AND PUBLIC LAW",
                        "DEPARTMENT OF JURISPRUDENCE AND PUBLIC LAW",
                    ),
                    (
                        "PRIVATE AND COMMERCIAL LAW",
                        "DEPARTMENT OF PRIVATE AND COMMERCIAL LAW",
                    ),
                    (
                        "INTERNATIONAL LAW AND SECURITY STUDIES",
                        "DEPARTMENT OF INTERNATIONAL LAW AND SECURITY STUDIES",
                    ),
                    ("ACCOUNTING", "DEPARTMENT OF ACCOUNTING"),
                    ("FINANCE", "DEPARTMENT OF FINANCE"),
                    (
                        "BUSINESS ADMINISTRATION AND MARKETING",
                        "DEPARTMENT OF BUSINESS ADMINISTRATION AND MARKETING",
                    ),
                    (
                        "INFORMATION RESOURCES MANAGEMENT",
                        "DEPARTMENT OF INFORMATION RESOURCES MANAGEMENT",
                    ),
                    (
                        "MATERNAL & CHILD HEALTH",
                        "DEPARTMENT OF MATERNAL & CHILD HEALTH",
                    ),
                    ("ADULT HEALTH", "DEPARTMENT OF ADULT HEALTH"),
                    (
                        "MENTAL HEALTH & PSYCHIATRY",
                        "DEPARTMENT OF MENTAL HEALTH & PSYCHIATRY",
                    ),
                    ("COMMUNITY HEALTH", "DEPARTMENT OF COMMUNITY HEALTH"),
                    ("MEDICAL LABORATORY", "DEPARTMENT OF MEDICAL LABORATORY SCIENCE"),
                    ("PUBLIC HEALTH", "DEPARTMENT OF PUBLIC HEALTH"),
                    (
                        "AGRICULTURE AND INDUSTRIAL TECHNOLOG",
                        "DEPARTMENT OF AGRICULTURE AND INDUSTRIAL TECHNOLOGY",
                    ),
                    ("BASIC SCIENCES", "DEPARTMENT OF BASIC SCIENCES"),
                    ("MICROBIOLOGY", "DEPARTMENT OF MICROBIOLOGY"),
                    ("Economics", "Department of Economics"),
                    ("Mass Communication", "Department of Mass Communication"),
                    ("Political Science", "Department of Political Science"),
                    ("Social Work", "Department of Social Work"),
                ],
                max_length=80,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
