# Generated by Django 4.1.5 on 2023-02-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_remove_usermodel_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="phone_number",
            field=models.CharField(default="+234 000 0000", max_length=16),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="password",
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
