# Generated by Django 4.1.5 on 2023-02-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_usermodel_phone_number_alter_usermodel_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
