# Generated by Django 4.1.5 on 2023-02-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_usermodel_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
