# Generated by Django 4.1.5 on 2023-02-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_alter_usermodel_date_of_birth_alter_usermodel_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="date_of_birth",
            field=models.DateField(max_length=8, null=True),
        ),
    ]
