# Generated by Django 4.1.3 on 2023-03-06 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_usermodel_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_a_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="position",
            field=models.CharField(
                choices=[("student", "student"), ("teacher", "teacher")],
                default="student",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(
                default="default@gmail.com",
                max_length=254,
                unique=True,
                validators=[student.models.UserModel.validate_email_domain],
                verbose_name="email",
            ),
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_number", models.CharField(max_length=10, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("admin", "administration"),
                            ("busary", "busary"),
                            ("security", "security"),
                            ("hall", "hall Adminstration"),
                            ("busa", "student Administration"),
                            ("bumu", "student Community Grade"),
                            ("registry", "registry"),
                            ("cafeteria", "Cafeteria"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
