# Generated by Django 4.1.5 on 2023-02-24 19:50

import complains.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplainsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complain_id",
                    models.UUIDField(
                        default=uuid.UUID("14900ad1-ee0a-403c-92a5-5335fd8718f8"),
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("admin", "administration"),
                            ("busary", "busary"),
                            ("security", "security"),
                            ("hall", "hall Adminstration"),
                            ("busa", "student Administration"),
                            ("bumu", "student Community Grade"),
                            ("registry", "registry"),
                            ("cafeteria", "Cafeteria"),
                        ],
                        max_length=30,
                    ),
                ),
                ("complain_message", models.TextField()),
                (
                    "complain_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=complains.models.ComplainsModel.upload,
                    ),
                ),
                (
                    "complain_status",
                    models.CharField(
                        choices=[
                            ("NOT SUBMITTED", "NOT SUBMITTEED"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("INITIALIZED", "INITIALIZED"),
                            ("RESOLVED", "RESOLVED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("FAILED", "FAILED"),
                            ("COMPLETED", "COMPLETED"),
                            ("START", "START"),
                        ],
                        default="START",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
