# Generated by Django 4.1.5 on 2023-02-24 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainsmodel",
            name="complain_id",
            field=models.UUIDField(
                default=uuid.UUID("8d4f881d-ef5f-44a5-8ac5-b9d33dc5d3cd"),
                editable=False,
                unique=True,
            ),
        ),
    ]
