# Generated by Django 4.1.5 on 2023-02-24 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0002_alter_complainsmodel_complain_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complainsmodel",
            name="complain_id",
        ),
        migrations.AlterField(
            model_name="complainsmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("38582fdf-d5c0-4398-bc8c-9635b186170c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
