# Generated by Django 4.1.5 on 2023-02-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0002_alter_complainsmodel_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complainsmodel",
            name="complain_state",
            field=models.CharField(
                choices=[
                    ("NOT SUBMITTED", "NOT SUBMITTEED"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("INITIALIZED", "INITIALIZED"),
                    ("RESOLVED", "RESOLVED"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("FAILED", "FAILED"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="INITIALIZED",
                max_length=20,
            ),
        ),
    ]
