# Generated by Django 4.1.5 on 2023-02-24 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0003_remove_complainsmodel_complain_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainsmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8f3112b3-adfa-4346-905c-a353a65406bb"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
