# Generated by Django 4.1.5 on 2023-02-27 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0005_alter_complainsmodel_complain_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainsmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9d3e769b-e933-4461-83da-83888843cd55"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
