# Generated by Django 4.1.3 on 2023-02-28 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("complains", "0008_alter_complainsmodel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainsmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d9e91aee-f766-4e08-b66f-fb6eca48c099"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
