# Generated by Django 4.1.5 on 2023-02-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_number", models.CharField(max_length=10, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("admin", "administration"),
                            ("busary", "busary"),
                            ("security", "security"),
                            ("hall", "hall Adminstration"),
                            ("busa", "student Administration"),
                            ("bumu", "student Community Grade"),
                            ("registry", "registry"),
                            ("cafeteria", "Cafeteria"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
